# Netlify configuration

[build]
  command = "pnpm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

# Bundle Node functions with esbuild (fast, supports TypeScript)
[functions]
  node_bundler = "esbuild"

# Proxy API requests to the serverless Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback to support React Router on refresh/deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
